# 还原论文算例

原文中计算$\varepsilon_{j}$的公式如下：

$$
\varepsilon_{j} > \max_{\substack{i \in \{1, \cdots, m \} \\ j \in \{1, \cdots, j - 1 \}}} \varepsilon_{k} \frac{(n - 1)^{2}}{4} \frac{\lvert \vec{v}_{k}^{H} A_{i} \vec{v}_{j} \rvert^{2}}{\lvert \operatorname{Re} (\lambda_{i,j}) \rvert \lvert \operatorname{Re} (\lambda_{i,k}) \rvert}
$$


## Example 1

两个子系统分别为

$$
A_{1} = \begin{bmatrix}
-1 & 0 & 0 \\
0 & -2 & 2 \\
0 & 0 & -2
\end{bmatrix}, \quad
A_{2} = \begin{bmatrix}
-3 & 0 & 0 \\
0 & -4 & 4 \\
0 & 0 & -6
\end{bmatrix}.
$$


In [1]:
from utils import *

A1 = torch.tensor([[-1, 0, 0], [0, -2, 2], [0, 0, -2]], dtype=torch.float32)
A2 = torch.tensor([[-3, 0, 0], [0, -4, 4], [0, 0, -6]], dtype=torch.float32)
A = (A1, A2)


计算invariant maximal flag信息

In [2]:
Example01 = ObtainInvariantMaximalFlag(A, device='cuda')
VVectors, LambdaMatrix = Example01.ComputeFlagInfo()
print(VVectors)
print(LambdaMatrix)


c:\Users\CTC\Desktop\temporary working library\Python\KoopmanCommonLyapunovFunction\utils.py:74: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Copy.cpp:250.)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')
tensor([[-1., -2., -2.],
        [-3., -4., -6.]], device='cuda:0')


输入一个初始的系数组合，迭代求解得到Common Lyapunov Function的系数

In [3]:
InitialCoeff = torch.tensor([1 / 9, 1 / 9, 1 / 8])
#Example01.LyapunovFunCoeff(InitialCoeff, PrintLog=True)
Example01.LyapunovFunCoeff(InitialCoeff)


tensor([0.1111, 0.1111, 0.1250], device='cuda:0')

We obtain the common Lyapunov function as follows:

$$
V(\vec{x}) = \frac{1}{9} x_{1}^{2} + \frac{1}{9} x_{2}^{2} + \frac{1}{9} x_{2}^{4}
$$


## Example 2

两个子系统分别为

$$
A_{1} = \begin{bmatrix}
-2 & 0 & 0 & 1 & 0 \\
0 & -2 & -1 & 0 & 0 \\
0 & 0 & -4 & 0 & 0 \\
0 & 0 & 0 & -4 & 0 \\
0 & 0 & 0 & 0 & -4
\end{bmatrix}, \quad
A_{2} = \begin{bmatrix}
-2 & 0 & 0 & 0 & 1 \\
0 & -1 & -1 & 0 & 0 \\
0 & 0 & -4 & 0 & 0 \\
0 & 0 & 0 & -3 & 0 \\
0 & 0 & 0 & 0 & -2
\end{bmatrix}.
$$


In [4]:
A1 = torch.tensor([[-2, 0, 0, 1, 0], [0, -2, -1, 0, 0], [0, 0, -4, 0, 0],
                   [0, 0, 0, -4, 0], [0, 0, 0, 0, -4]],
                  dtype=torch.float32)
A2 = torch.tensor([[-2, 0, 0, 0, 1], [0, -1, -1, 0, 0], [0, 0, -4, 0, 0],
                   [0, 0, 0, -3, 0], [0, 0, 0, 0, -2]],
                  dtype=torch.float32)
A = (A1, A2)


计算invariant maximal flag信息

In [5]:
Example02 = ObtainInvariantMaximalFlag(A, device="gpu")
VVectors, LambdaMatrix = Example02.ComputeFlagInfo()
print(VVectors)
print(LambdaMatrix)


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[-2., -2., -4., -4., -4.],
        [-2., -1., -4., -3., -2.]])


输入一个初始的系数组合，迭代求解得到Common Lyapunov Function的系数

In [6]:
InitialCoeff = torch.tensor([1 / 25, 1 / 25, 1 / 24, 1 / 47, 1 / 46])
Example02.LyapunovFunCoeff(InitialCoeff,PrintLog=True)


j = 1 

initial value = 0.04 

value = 0.04 

j = 2 

initial value = 0.04 

i = 1 , j = 2 , k = 1 , value = 0.0
i = 2 , j = 2 , k = 1 , value = 0.0

Value should be 0.04 

j = 3 

initial value = 0.041666668 

i = 1 , j = 3 , k = 1 , value = 0.0
i = 1 , j = 3 , k = 2 , value = 0.02
i = 2 , j = 3 , k = 1 , value = 0.0
i = 2 , j = 3 , k = 2 , value = 0.04

Value should be 0.041666668 

j = 4 

initial value = 0.021276595 

i = 1 , j = 4 , k = 1 , value = 0.02
i = 1 , j = 4 , k = 2 , value = 0.0
i = 1 , j = 4 , k = 3 , value = 0.0
i = 2 , j = 4 , k = 1 , value = 0.0
i = 2 , j = 4 , k = 2 , value = 0.0
i = 2 , j = 4 , k = 3 , value = 0.0

Value should be 0.021276595 

j = 5 

initial value = 0.02173913 

i = 1 , j = 5 , k = 1 , value = 0.0
i = 1 , j = 5 , k = 2 , value = 0.0
i = 1 , j = 5 , k = 3 , value = 0.0
i = 1 , j = 5 , k = 4 , value = 0.0
i = 2 , j = 5 , k = 1 , value = 0.04
i = 2 , j = 5 , k = 2 , value = 0.0
i = 2 , j = 5 , k = 3 , value = 0.0
i = 2 , j = 5 , k = 4 , value = 0.0


tensor([0.0400, 0.0400, 0.0417, 0.0213, 0.0400])

We obtain the common Lyapunov function as follows:

$$
V(\vec{x}) = \frac{1}{25} x_{1}^{2} + \frac{1}{25} x_{2}^{2} + \frac{1}{24} x_{1}^{4} + \frac{1}{47} x_{1}^{2} x_{2}^{2} + \frac{1}{25} x_{2}^{4}
$$
